name: Nginx Submodule Update

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Welcome to NGINX Workflow"

  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Echo Email
        run: echo "Sending Email"
        
      - name: Send Email
        uses: dawidd6/action-send-mail@v2.0.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_GMAIL }}
          password: ${{ secrets.PASSWORD_GMAIL }}
          subject: "NGINX Workflow: Email Notification"
          body: "NGINX Workflow: Email Notification"
          to: ${{ secrets.RECEIVER_EMAIL }}
          from: ${{ secrets.EMAIL_GMAIL }}

  update_Tech_n_Learnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Echo Hello
        run: echo "Lets update Tech n Learnings Submodules"

      - name: Setup the Git Config
        run: |
          git config --global user.email ${{ secrets.EMAIL_GITHUB }}
          git config --global user.name ${{ secrets.USERNAME_GITHUB }}

      - name: Clone Tech n Learnings
        run: |
          git clone https://github.com/DhairyaHans/Tech-n-Learnings.git
          cd Tech-n-Learnings
          git submodule update --init --recursive
          git submodule update --remote ./nginx/nginx-basics
          git restore --staged .
          echo "Restored"
          git add .
          echo "Add"
          git status
          git commit -am "NGINX Workflow: Updated Tech n Learning, NGINX submodule"
          echo "Committed"
          git status
          echo "Push"
          git push origin main
  