name: Nginx Submodule Update

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Welcome to NGINX Workflow"

  update_Tech_n_Learnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Echo Hello
        run: echo "Lets update Tech n Learnings Submodules"

      - name: Setup the Git Config
        run: |
          git config --global user.email ${{ secrets.EMAIL_GITHUB }}
          git config --global user.name ${{ secrets.USERNAME_GITHUB }}

      - name: Clone Tech n Learnings
        run: |
          git clone --recurse-submodules https://${{ secrets.PAT }}@github.com/DhairyaHans/Tech-n-Learnings.git
          cd Tech-n-Learnings
          git submodule update --remote --merge ./nginx/nginx-basics
          git restore --staged .
          echo "Restored"
          git add .
          echo "Add"
          git status
          git commit -am "NGINX Workflow: Updated Tech n Learning, NGINX submodule"
          echo "Committed"
          git status
          echo "Push"
          git push origin main
  